drop table if exists bseed_trade_permits cascade;

create table bseed_trade_permits as (
    select 
        permit_no,             
        permit_issued,        
        permit_expire,         
        permit_completed,      
        permit_status,         
        site_address,          
        between1,              
        parcel_no,             
        prc_lot,               
        prc_subdiv,            
        case_type,             
        case_description,      
        legal_use,             
        estimated_cost,        
        parcel_size,           
        parcel_cluster_sector, 
        stories,               
        parcel_floor_area,     
        parcel_ground_area,    
        prc_aka_address,       
        elv_type_of_work,              
        permit_description,    
        fdicn_description,     
        elv_type_of_use,               
        residential,           
        description,           
        elv_type_const_cod,    
        elv_zoning_dist,       
        elv_use_group,        
        elv_basement,          
        fee_type,              
        csm_caseno,            
        csf_created_by,        
        seq_no,                
        pcf_amt_due,           
        owner_name,            
        owner_address1,       
        contractor_last_name,  
        contractor_address1 
    from bseed_elevator union all
    select
        permit_no,             
        permit_applied,        
        permit_expire,         
        permit_completed,      
        permit_status,         
        site_address,          
        between1,              
        parcel_no,             
        prc_lot,               
        prc_subdiv,            
        case_type,             
        case_description,      
        legal_use,             
        estimated_cost,        
        parcel_size,           
        parcel_cluster_sector, 
        stories,               
        parcel_floor_area,     
        parcel_ground_area,    
        prc_aka_address,       
        plm_work,              
        permit_description,    
        fdicn_description,     
        plm_use,               
        residential,           
        description,           
        plm_type_const_cod,    
        plm_zoning_dist,       
        plm_use_group,        
        plm_basement,          
        fee_type,              
        csm_caseno,            
        csf_created_by,        
        seq_no,                
        pcf_amt_due,           
        owner_name,            
        owner_address1,       
        contractor_last_name,  
        contractor_address1
    from bseed_plumbing union all
    select
        permit_no,             
        permit_issued,        
        permit_expire,         
        permit_completed,      
        permit_status,         
        site_address,          
        between1,              
        parcel_no,             
        prc_lot,               
        prc_subdiv,            
        case_type,             
        case_description,      
        legal_use,             
        estimated_cost,        
        parcel_size,           
        parcel_cluster_sector, 
        stories,               
        parcel_floor_area,     
        parcel_ground_area,    
        prc_aka_address,       
        ele_type_work,              
        permit_description,    
        fdicn_description,     
        ele_type_use,               
        residential,           
        description,           
        ele_type_const_cod,    
        ele_zoning_dist,       
        ele_use_group,        
        ele_basement,          
        fee_type,              
        csm_caseno,            
        csf_created_by,        
        seq_no,                
        pcf_amt_due,           
        owner_name,            
        owner_address1,       
        contractor_last_name,  
        contractor_address1
    from bseed_electrical union all
    select
        permit_no,             
        permit_issued,        
        permit_expire,         
        permit_completed,      
        permit_status,         
        site_address,          
        between1,              
        parcel_no,             
        prc_lot,               
        prc_subdiv,            
        case_type,             
        case_description,      
        legal_use,             
        estimated_cost,        
        parcel_size,           
        parcel_cluster_sector, 
        stories,               
        parcel_floor_area,     
        parcel_ground_area,    
        prc_aka_address,       
        bpv_type_work,              
        permit_description,    
        fdicn_description,     
        bpv_type_use,               
        residential,           
        description,           
        bpv_type_const_cod,    
        bpv_zoning_dist,       
        bpv_use_group,        
        bpv_basement,          
        fee_type,              
        csm_caseno,            
        csf_created_by,        
        seq_no,                
        pcf_amt_due,           
        concat_ws(' ', owner_first_name, owner_last_name),            
        owner_address1,       
        contractor_last_name,  
        contractor_address1
    from bseed_boiler union all
    select
        permit_no,             
        permit_issued,        
        permit_expire,         
        permit_completed,      
        permit_status,         
        site_address,          
        between1,              
        parcel_no,             
        prc_lot,               
        prc_subdiv,            
        case_type,             
        case_description,      
        legal_use,             
        estimated_cost,        
        parcel_size,           
        parcel_cluster_sector, 
        stories,               
        parcel_floor_area,     
        parcel_ground_area,    
        prc_aka_address,       
        mec_work,              
        permit_description,    
        fdicn_description,     
        mec_use,               
        residential,           
        description,           
        mec_type_const_cod,    
        mec_zoning_dist,       
        mec_use_group,        
        mec_basement,          
        fee_type,              
        csm_caseno,            
        csf_created_by,        
        seq_no,                
        pcf_amt_due,           
        owner_name,            
        owner_address1,       
        contractor_last_name,  
        contractor_address1
    from bseed_mechanical
);

alter table bseed_trade_permits rename column elv_type_of_work to type_of_work;
alter table bseed_trade_permits rename column elv_type_of_use to type_of_use;
alter table bseed_trade_permits rename column elv_type_const_cod to type_const_cod;
alter table bseed_trade_permits rename column elv_zoning_dist to zoning_dist;
alter table bseed_trade_permits rename column elv_use_group to use_group;
alter table bseed_trade_permits rename column elv_basement to basement;

alter table bseed_trade_permits add column uniq serial primary key;

-- trim large spaces
update bseed_trade_permits set 
    site_address = regexp_replace(site_address, '[\s]{2,}', ' '),
    owner_address1 = regexp_replace(owner_address1, '[\s]{2,}', ' '),
    contractor_address1 = regexp_replace(contractor_address1, '[\s]{2,}', ' ');

select addgeometrycolumn('bseed_trade_permits', 'geom', 4326, 'POINT', 2);
create index if not exists bseed_trade_permits_geom_idx on bseed_trade_permits using gist(geom);

update bseed_trade_permits t set geom =
    (select ST_Transform(ST_Centroid(wkb_geometry), 4326) from base.joined p where t.parcel_no = p.parcelno limit 1);

update bseed_trade_permits t set geom =
    (select ST_Transform(ST_Centroid(wkb_geometry), 4326) from base.joined p where t.site_address = p.propaddr limit 1)
    where geom is null;



